"""add recommendations table (Hito 3 Sprint 2)

Revision ID: 03c9a9948d19
Revises: 0ca98195a339
Create Date: 2026-07-31 14:40:36.929561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03c9a9948d19'
down_revision: Union[str, None] = '0ca98195a339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'ACCEPTED', 'DISCARDED', name='recommendationstatus'), nullable=False),
    sa.Column('primary_evaluation', sa.JSON(), nullable=True),
    sa.Column('alternative_evaluations', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=True),
    sa.Column('narrative_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_step', sa.JSON(), nullable=True),
    sa.Column('decision_engine_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommendation_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['migration_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_assessment_id'), 'recommendations', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_recommendations_case_id'), 'recommendations', ['case_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_case_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_assessment_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
