"""add assessments and domain_events (Hito 2, Decision Engine)

Revision ID: 0ca98195a339
Revises: 4b1a3e304185
Create Date: 2026-07-11 11:57:52.716400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ca98195a339'
down_revision: Union[str, None] = '4b1a3e304185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_name'), 'domain_events', ['name'], unique=False)
    op.create_index(op.f('ix_domain_events_occurred_at'), 'domain_events', ['occurred_at'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('decision_engine_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['migration_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_case_id'), 'assessments', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_case_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_domain_events_occurred_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_name'), table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
