"""add email verification and password reset fields

Revision ID: 228566482b6c
Revises: 9b4fb4593b48
Create Date: 2026-09-05 03:38:37.899914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 -- autogenerate emite sqlmodel.sql.sqltypes pero omite el import


# revision identifiers, used by Alembic.
revision: str = '228566482b6c'
down_revision: Union[str, None] = '9b4fb4593b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_column('user', 'password_reset_expires_at')
    op.drop_column('user', 'password_reset_token')
    op.drop_column('user', 'email_verification_expires_at')
    # ### end Alembic commands ###
