"""add migration_cases and case_family_members (Sprint 1, Case Engine)

Revision ID: 4b1a3e304185
Revises: 85423f31211a
Create Date: 2026-07-10 08:36:12.961386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b1a3e304185'
down_revision: Union[str, None] = '85423f31211a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('objective_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('objective_visa_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_step_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_cases_status'), 'migration_cases', ['status'], unique=False)
    op.create_index(op.f('ix_migration_cases_user_id'), 'migration_cases', ['user_id'], unique=True)
    op.create_table('case_family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['migration_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_family_members_case_id'), 'case_family_members', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_family_members_case_id'), table_name='case_family_members')
    op.drop_table('case_family_members')
    op.drop_index(op.f('ix_migration_cases_user_id'), table_name='migration_cases')
    op.drop_index(op.f('ix_migration_cases_status'), table_name='migration_cases')
    op.drop_table('migration_cases')
    # ### end Alembic commands ###
