"""add zillow listings

Revision ID: 716b0d6fb62b
Revises: 302f713f2977
Create Date: 2026-01-01 09:31:45.595877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '716b0d6fb62b'
down_revision: Union[str, None] = '302f713f2977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zillow_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zipcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('beds', sa.Float(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('metadata_blob', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zillow_listings_listing_id'), 'zillow_listings', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zillow_listings_listing_id'), table_name='zillow_listings')
    op.drop_table('zillow_listings')
    # ### end Alembic commands ###
