"""add execution_plans and plan_steps (Hito 4 Sprint 1)

Revision ID: 9b4fb4593b48
Revises: 03c9a9948d19
Create Date: 2026-08-01 13:24:35.523650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b4fb4593b48'
down_revision: Union[str, None] = '03c9a9948d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='executionplanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['migration_cases.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_plans_case_id'), 'execution_plans', ['case_id'], unique=False)
    op.create_index(op.f('ix_execution_plans_recommendation_id'), 'execution_plans', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_execution_plans_status'), 'execution_plans', ['status'], unique=False)
    op.create_table('plan_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='planstepstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_plan_id'], ['execution_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_steps_execution_plan_id'), 'plan_steps', ['execution_plan_id'], unique=False)
    op.create_index(op.f('ix_plan_steps_status'), 'plan_steps', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_steps_status'), table_name='plan_steps')
    op.drop_index(op.f('ix_plan_steps_execution_plan_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_execution_plans_status'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_recommendation_id'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_case_id'), table_name='execution_plans')
    op.drop_table('execution_plans')
    # ### end Alembic commands ###
